#!/bin/bash
#SBATCH --job-name=trimm
#SBATCH --cpus-per-task=8
#SBATCH --output=log_trimm.txt

srun module load trimmomatic/0.38
for r1_file in ./*/*_R1_*.fastq.gz; do
r2_file="${r1_file/_R1_/_R2_}"
srun java -jar /opt/trimmomatic-0.38/trimmomatic-0.38.jar PE -threads 8 -phred33 "$r1_file" "$r2_file" "$r1_file"_paired "$r1_file"_unpaired "$r2_file"_paired "$r2_file"_unpaired ILLUMINACLIP:/opt/trimmomatic-0.38/adapters/TruSeq3-PE-2.fa:2:30:10
done